### ISSUE TITLE
libbluray 1.1.2

### ISSUE THREAD

**Issue by fandangos** [ShiftMediaProject/libbluray#1]
Hi, 

Would it be possible to have a pre built static library for the latest libbluray version: 1.1.2?

**Comment by Sibras** [comment]
Its on the todo list. But the update to the 1.1.x versions required a fair amount of work that I just haven't been able to prioritise yet.

**Comment by fandangos** [comment]
Thanks your work is really appreciated. It makes possible to update the libraries on my Kodi build.

I took your SMP folder and added all the files from 1.1.2.
I was able to compile it and it seems to be working but I'm new into coding and compiling so a version made by someone more experienced like you is really welcome.

**Comment by Sibras** [comment]
Done
