### ISSUE TITLE
Hope to increase support for kxml2

### ISSUE THREAD

**Issue by john-wrick** [ShiftMediaProject/libbluray#3]
Libbluray is very good. I hope to add support for kxml2. Many Bluray discs, such as, Patriots Day 2016 UHD、Journey to the South Pacific 2013、Turtle Odyssey 2018，etc., need kxmlparser to display Bluray menu.

**Comment by MediaBrasil** [comment]
@Sibras, thanks, any chance to share the new version 1.2.1.
